### ISSUE TITLE
Watcher output error when there isn't pods

### ISSUE THREAD

**Issue by hustcat** [openvswitch/ovn-kubernetes#187]
Watcher output error when there is not pods:

```
2018-01-03T07:59:44.185Z |  0  | watcher | ERR | failed in _sync_k8s_pods ('NoneType' object is not iterable)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ovn_k8s/watcher/watcher.py", line 82, in _sync_k8s_pods
    mode.sync_pods(pods)
  File "/usr/lib/python2.7/site-packages/ovn_k8s/modes/overlay.py", line 499, in sync_pods
    for pod in pods:
TypeError: 'NoneType' object is not iterable
```

**Comment by rajatchopra** [comment]
which version of kubernetes are you using?

**Comment by shettyg** [comment]
We moved from python to golang.
