### ISSUE TITLE
go-controller - ovnkube node-init fails when -init-gateways true 

### ISSUE THREAD

**Issue by bsteciuk** [openvswitch/ovn-kubernetes#224]
When running `ovnkube --init-node` with `-init-gateways is true (full --init-node command below)
```
./ovnkube --init-node bsteciuk-worker-linux -ca-cert "/etc/kubernetes/pki/ca.crt" \
 -token "${TOKEN}" -apiserver "https://10.142.0.10:6443" \
 -ovn-north-db "tcp://10.142.0.10:6641" -ovn-south-db "tcp://10.142.0.10:6642" \
 -init-gateways true -gateway-interface ens4 -nodeport true
```
 ovnkube fails with the following:

```
INFO[0000] Node bsteciuk-worker-linux ready for ovn initialization with subnet 10.111.2.0/24 
Feb 13 16:29:40 bsteciuk-worker-linux systemd[1]: Started LSB: Open vSwitch switch.
Feb 13 16:29:40 bsteciuk-worker-linux ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl set Open_vSwitch . "external_ids:ovn-nb=\"tcp:10.142.0.10:6641\"" "external_ids:ovn-remote=\"tcp:10.142.0.10:6642\"" external_ids:ovn-encap-ip=10.142.0.11 "external_ids:ovn-encap-type=\"geneve\"" "external_ids:k8s-api-server=\"https://10.142.0.10:6443\"" "external_ids:k8s-api-token=\"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvdm4tY29udHJvbGxlci10b2tlbi10aDQ2cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJvdm4tY29udHJvbGxlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjZmOTY5NzdiLTEwY2UtMTFlOC1hNDM1LTQyMDEwYThlMDAwYSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpvdm4tY29udHJvbGxlciJ9.YRYutvUR1uBSAVA227r1ThgJ8GrwGwMdR9o8cIgRdpqQc_ScFn9dKaji-rAMhcxyqDOXeYUi1UZBY_CHIhoIimZiHC3TN-9evsyKvlRmFR9OG_kvQ9zVhwy3gq-VqA2uDbzEQxH-mGDmytyFdQc4zTxVeHAzWl375GHhf3KmHY0ZyobG4aG4MHbOvbgQpsqrlwbEUFB8XUdcr81EBklNcotzhP8YoGO1Ryo0ObMx4UMGNzXBNO9cAYFmBUMwW57ZR_qYFcZ243FSv51TsaV3qjebVKs0I89m3K7nZtaDRFdbTTXSAG7WU8nNZ6czaDHozf4JUYzAGGkO5Ednamf_2w\""
Feb 13 16:29:40 bsteciuk-worker-linux systemd[1]: Stopping LSB: OVN host components...
Feb 13 16:29:40 bsteciuk-worker-linux ovn-host[7357]:  * Exiting ovn-controller (3818)
Feb 13 16:29:40 bsteciuk-worker-linux kernel: [ 4624.020155] device genev_sys_6081 left promiscuous mode
Feb 13 16:29:40 bsteciuk-worker-linux systemd[1]: Stopped LSB: OVN host components.
Feb 13 16:29:40 bsteciuk-worker-linux systemd[1]: Starting LSB: OVN host components...
Feb 13 16:29:40 bsteciuk-worker-linux ovn-host[7385]:  * Starting ovn-controller
INFO[0000] Open configuration file /etc/openvswitch/ovn_k8s.conf error: open /etc/openvswitch/ovn_k8s.conf: no such file or directory, use default values 
Feb 13 16:29:40 bsteciuk-worker-linux systemd[1]: Started LSB: OVN host components.
Feb 13 16:29:40 bsteciuk-worker-linux ovn-nbctl: ovs|00001|nbctl|INFO|Called as /usr/bin/ovn-nbctl --db=tcp:10.142.0.10:6641 --timeout=5 -- --may-exist ls-add bsteciuk-worker-linux -- set logical_switch bsteciuk-worker-linux other-config:subnet=10.111.2.0/24 external-ids:gateway_ip=10.111.2.1/24
Feb 13 16:29:40 bsteciuk-worker-linux kernel: [ 4624.168322] device genev_sys_6081 entered promiscuous mode
Feb 13 16:29:40 bsteciuk-worker-linux ovn-nbctl: ovs|00001|nbctl|INFO|Called as /usr/bin/ovn-nbctl --db=tcp:10.142.0.10:6641 --timeout=5 -- --may-exist lsp-add bsteciuk-worker-linux stor-bsteciuk-worker-linux -- set logical_switch_port stor-bsteciuk-worker-linux type=router options:router-port=rtos-bsteciuk-worker-linux "addresses=\"00:00:00:3E:0F:34\""
Feb 13 16:29:40 bsteciuk-worker-linux systemd-udevd[7429]: Could not generate persistent MAC address for genev_sys_6081: No such file or directory
Feb 13 16:29:40 bsteciuk-worker-linux ovs-vsctl: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl --timeout=5 -- --may-exist add-br br-int
Feb 13 16:29:40 bsteciuk-worker-linux ovs-vsctl: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl --timeout=5 -- --may-exist add-port br-int k8s-bsteciuk-wo -- set interface k8s-bsteciuk-wo type=internal mtu_request=1400 external-ids:iface-id=k8s-bsteciuk-worker-linux
Feb 13 16:29:40 bsteciuk-worker-linux ovn-nbctl: ovs|00001|nbctl|INFO|Called as /usr/bin/ovn-nbctl --db=tcp:10.142.0.10:6641 --timeout=5 -- --may-exist lsp-add bsteciuk-worker-linux k8s-bsteciuk-worker-linux -- lsp-set-addresses k8s-bsteciuk-worker-linux "e2:4d:21:c3:f6:15 10.111.2.2"
Feb 13 16:29:41 bsteciuk-worker-linux ovn-nbctl: ovs|00001|nbctl|INFO|Called as /usr/bin/ovn-nbctl --db=tcp:10.142.0.10:6641 --timeout=5 set logical_switch bsteciuk-worker-linux load_balancer=cf9f654e-aa26-4b42-ba7b-69499507fa34
Feb 13 16:29:41 bsteciuk-worker-linux ovn-nbctl: ovs|00001|nbctl|INFO|Called as /usr/bin/ovn-nbctl --db=tcp:10.142.0.10:6641 --timeout=5 add logical_switch bsteciuk-worker-linux load_balancer 418b52f5-6d19-4611-a991-65b8f0b0d8b2
Feb 13 16:29:41 bsteciuk-worker-linux ovs-vsctl: ovs|00001|vsctl|INFO|Called as /usr/bin/ovs-vsctl --timeout=5 -- --may-exist add-br brens4 -- br-set-external-id brens4 bridge-id brens4 -- set bridge brens4 fail-mode=standalone other_config:hwaddr=42:01:0a:8e:00:0b -- --may-exist add-port brens4 ens4
INFO[0000] Successfully created OVS bridge "brens4"     
INFO[0000] Successfully saved addr "10.142.0.11/32 brens4" to bridge "brens4" 
Feb 13 16:29:41 bsteciuk-worker-linux kernel: [ 4624.246838] device brens4 entered promiscuous mode
Feb 13 16:29:41 bsteciuk-worker-linux kernel: [ 4624.247086] device ens4 entered promiscuous mode
ERRO[0000] Add route to bridge "brens4" failed: network is unreachable 
ERRO[0000] Failed to convert nic ens4 to OVS bridge (network is unreachable) 
panic: Failed to convert nic ens4 to OVS bridge (network is unreachable)

goroutine 1 [running]:
main.main()
	/home/bsteciuk/go/src/github.com/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:177 +0x181c
```

It looks like the failure is occurring in nicstobridge.go:51 with `network is unreachable` while trying to add route to the ovs bridge.  I don't see this failure when `-init-gateways true` is not set.

Worth noting, that this leaves the node in a state where it can no longer be access via network, nor can it make connections out.  This was on a cluster running in GCE.

**Comment by shettyg** [comment]
@bsteciuk 

3 questions/comments
1. How many interfaces do you have in your box? 

2. If you have more than one interface, is ens4 your primary interface? i.e one with default gateway configured?

3. If you have more than one interface, and ens4 is not your primary interface, you should likely have to provide the default gateway for ens4 as part of the -node-init command.

**Comment by shettyg** [comment]
For e.g:
https://github.com/openvswitch/ovn-kubernetes/blob/master/vagrant/provisioning/setup-k8s-minion.sh#L86

**Comment by bsteciuk** [comment]
@shettyg  it's just the one interface `ens4`

**Comment by shettyg** [comment]
Okay. It is possible that, because GCE has the /32 interface, the code to convert interface from nic to bridge is buggy. It may be missing an additional step. Let me look into it.

**Comment by shettyg** [comment]
@bsteciuk 
I do not have a GCE machine handy. My local simulation with a /32 interface seems to work with the above referenced patch.
