### ISSUE TITLE
randomly failing to get pod annotations

### ISSUE THREAD

**Issue by mihail-velikov** [openvswitch/ovn-kubernetes#261]
Hello all,

We are experiencing very strange networking problem where from time to time the containers fail to start. Currently we are using a mixed environment of both Linux and Windows nodes running kubernetes 1.9.4 and opevswitch 2.7.2 on ubuntu 16.04 kernel 4.13.

The problems seems to be with ovn-watcher and here is the error from the master node:
```
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovs|  0  | watcher | ERR | failed in _sync_k8s_pods ('annotations')#012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/watcher/watcher.py", line 82, in _sync_k8s_pods#012    mode.sync_pods(pods)#012  File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/modes/overlay.py", line 503, in sync_pods#012    annotations = pod['metadata']['annotations']#012KeyError: 'annotations'
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]: 2018-03-19T14:44:31Z |  0  | watcher | ERR | failed in _sync_k8s_pods ('annotations')
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]: Traceback (most recent call last):
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]:   File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/watcher/watcher.py", line 82, in _sync_k8s_pods
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]:     mode.sync_pods(pods)
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]:   File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/modes/overlay.py", line 503, in sync_pods
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]:     annotations = pod['metadata']['annotations']
Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]: KeyError: 'annotations' 
```

On the node where the container is scheduled it gives these error messages:
```
Mar 19 08:33:06 esd-kbrnts-lnx-4 kubelet[24887]: W0319 08:33:06.742046   24887 pod_container_deletor.go:77] Container "b886045faec5c417d5bc81260d46df663fe38e1044f15d61be333252f590ba01" not found in pod's containers
Mar 19 08:33:06 esd-kbrnts-lnx-4 kubelet[24887]: I0319 08:33:06.856666   24887 reconciler.go:191] operationExecutor.UnmountVolume started for volume "default-token-6h8jr" (UniqueName: "kubernetes.io/secret/5a0d6251-2921-11e8-94b9-00155d00680b-default-token-6h8jr") pod "5a0d6251-2921-11e8-94b9-00155d00680b" (UID: "5a0d6251-2921-11e8-94b9-00155d00680b")
Mar 19 08:33:06 esd-kbrnts-lnx-4 kubelet[24887]: I0319 08:33:06.880413   24887 operation_generator.go:643] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/5a0d6251-2921-11e8-94b9-00155d00680b-default-token-6h8jr" (OuterVolumeSpecName: "default-token-6h8jr") pod "5a0d6251-2921-11e8-94b9-00155d00680b" (UID: "5a0d6251-2921-11e8-94b9-00155d00680b"). InnerVolumeSpecName "default-token-6h8jr". PluginName "kubernetes.io/secret", VolumeGidValue ""
Mar 19 08:33:06 esd-kbrnts-lnx-4 kubelet[24887]: I0319 08:33:06.956969   24887 reconciler.go:297] Volume detached for volume "default-token-6h8jr" (UniqueName: "kubernetes.io/secret/5a0d6251-2921-11e8-94b9-00155d00680b-default-token-6h8jr") on node "esd-kbrnts-lnx-4" DevicePath ""
ar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: I0319 09:36:42.498561   24887 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "admin-token-nct75" (UniqueName: "kubernetes.io/secret/f1065f4e-2b82-11e8-94b9-00155d00680b-admin-token-nct75") pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg" (UID: "f1065f4e-2b82-11e8-94b9-00155d00680b")
Mar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: I0319 09:36:42.499666   24887 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "kubernetes-dashboard-certs" (UniqueName: "kubernetes.io/secret/f1065f4e-2b82-11e8-94b9-00155d00680b-kubernetes-dashboard-certs") pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg" (UID: "f1065f4e-2b82-11e8-94b9-00155d00680b")
Mar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: I0319 09:36:42.500188   24887 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "tmp-volume" (UniqueName: "kubernetes.io/empty-dir/f1065f4e-2b82-11e8-94b9-00155d00680b-tmp-volume") pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg" (UID: "f1065f4e-2b82-11e8-94b9-00155d00680b")
Mar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: W0319 09:36:42.634908   24887 raw.go:87] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/system.slice/run-r582f2f477243454cad81b5551afad3b7.scope": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory
Mar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: W0319 09:36:42.635203   24887 raw.go:87] Error while processing event ("/sys/fs/cgroup/blkio/system.slice/run-r582f2f477243454cad81b5551afad3b7.scope": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory
Mar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: W0319 09:36:42.635445   24887 raw.go:87] Error while processing event ("/sys/fs/cgroup/memory/system.slice/run-r582f2f477243454cad81b5551afad3b7.scope": 0x40000100 == IN_CREATE|IN_ISDIR): readdirent: no such file or directory
Mar 19 09:36:42 esd-kbrnts-lnx-4 kubelet[24887]: W0319 09:36:42.635497   24887 raw.go:87] Error while processing event ("/sys/fs/cgroup/devices/system.slice/run-r582f2f477243454cad81b5551afad3b7.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/system.slice/run-r582f2f477243454cad81b5551afad3b7.scope: no such file or directory
Mar 19 09:36:42 esd-kbrnts-lnx-4 dockerd[7394]: time="2018-03-19T09:36:42.781909311-05:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/8e103400246d7d77c49571b75de47bfde7897f5614d9ad391fa81ce580b12794-init: exec: \"auplink\": executable file not found in $PATH"
Mar 19 09:36:42 esd-kbrnts-lnx-4 dockerd[7394]: time="2018-03-19T09:36:42.863871869-05:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/8e103400246d7d77c49571b75de47bfde7897f5614d9ad391fa81ce580b12794: exec: \"auplink\": executable file not found in $PATH"
Mar 19 09:36:47 esd-kbrnts-lnx-4 ovs|  31 | ovn-k8s-cni-overlay | ERR | {"cniVersion": "0.1.0", "code": 100, "message": "failed to get pod annotation"}
Mar 19 09:36:47 esd-kbrnts-lnx-4 kubelet[24887]: 2018-03-19T14:36:47Z |  31 | ovn-k8s-cni-overlay | ERR | {"cniVersion": "0.1.0", "code": 100, "message": "failed to get pod annotation"}
Mar 19 09:36:47 esd-kbrnts-lnx-4 kubelet[24887]: E0319 09:36:47.985423   24887 cni.go:259] Error adding network:
Mar 19 09:36:47 esd-kbrnts-lnx-4 kubelet[24887]: E0319 09:36:47.985482   24887 cni.go:227] Error while adding to cni network:
Mar 19 09:36:48 esd-kbrnts-lnx-4 kubelet[24887]: E0319 09:36:48.154909   24887 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system" network:
Mar 19 09:36:48 esd-kbrnts-lnx-4 kubelet[24887]: E0319 09:36:48.155078   24887 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system(f1065f4e-2b82-11e8-94b9-00155d00680b)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system" network:
Mar 19 09:36:48 esd-kbrnts-lnx-4 kubelet[24887]: E0319 09:36:48.155107   24887 kuberuntime_manager.go:647] createPodSandbox for pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system(f1065f4e-2b82-11e8-94b9-00155d00680b)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system" network:
Mar 19 09:36:48 esd-kbrnts-lnx-4 kubelet[24887]: E0319 09:36:48.155231   24887 pod_workers.go:186] Error syncing pod f1065f4e-2b82-11e8-94b9-00155d00680b ("dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system(f1065f4e-2b82-11e8-94b9-00155d00680b)"), skipping: failed to "CreatePodSandbox" for "dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system(f1065f4e-2b82-11e8-94b9-00155d00680b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system(f1065f4e-2b82-11e8-94b9-00155d00680b)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"dashboard-v1-kubernetes-dashboard-667c5d9fd7-r4kjg_kube-system\" network: "
```

Restarting the ovn-k8s-watcher seems to fix the problem.

Another issues:
Randomly new containers scheduled on a windows node do not have network connectivity. Previously deployed containers work as expected. The node running the container has network connectivity to the overlay also.

I have tried restarting the docker service, the service for openvswitch and the kubernetes services and none of this helped. Rebooting the node itself resolves the problem.

Any input/ideas would be greatly appreciated!

**Comment by rajatchopra** [comment]
Please try the golang based implementation now. The python code is being deprecated. The docs are already changed to reflect that.

**Comment by shettyg** [comment]
>>Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]:     annotations = pod['metadata']['annotations']
>>Mar 19 09:44:31 esd-kbrnts-lnx-1 ovn-k8s-watcher[202394]: KeyError: 'annotations' 

The above error is coming because the pod object does not have 'annotations' key in it. The code expectation was that it will always have the key 'annotations' (though the value itself may be empty) and looks like that assumption is wrong.

Further, the kubelet is complaining that the IP addresses is not being received and this is happening because the watcher is not created OVN logical port.

But the exception should not be catastrophic as it is being exception handled and future pods should continue to get a OVN logical port created. Can you paste the entire watcher log? May be all pods are not getting annotations.

**Comment by mihail-velikov** [comment]
Hello guys,

Thank you very much for the quick response.

@shettyg  - I read the code that produces the error message when we first got it (in January). Since then when we get the error I was just restarting the watcher and things were back to fine. After the first error message about annotations is displayed in the log no containers provisioned will have network connectivity. I have checked that the annotation exist by describing the pods and comparing to a working pod. After restarting the watcher the annotations are not changed and the pod is the same (I mean it is not killed or moved to another host) - it starts with no problem.

I am pretty sure that I can replicate the problem relatively easily and I think it is related to another problem that we experience on windows. When deleting a pod that runs on a windows node it stays in "Terminating" state but it is actually successfully removed from the node. In order to free up resources I need to use delete the pod with "--grace-period=0 --force". I believe that after several forceful deletes it gets messed up and breaks the parsing of the annotations. 

I will reinstall the cluster today to check if the golang based implementation will resolve the problem.

Thank you very much again :)

**Comment by mihail-velikov** [comment]
Hello again :)

I am trying to use the golang implementations of the controller at the moment but containers are staying in a ContainerCreating state due to a problem with the CNI.

A little bit more information about my setup:
- I have 2 nodes - master-10.31.0.30 and worker 10.31.0.32

When I try to add a new pod on the master:
syslog:
```
Mar 21 04:04:45 esd-kbrnts-lnx-1 ovn-nbctl: ovs|00001|nbctl|INFO|Called as ovn-nbctl --wait=sb -- --may-exist lsp-add esd-kbrnts-lnx-3 default_busybox -- lsp-set-addresses default_busybox dynamic -- set logical_switch_port default_busybox external-ids:namespace=default external-ids:logical_switch=esd-kbrnts-lnx-3 external-ids:pod=true
Mar 21 04:04:45 esd-kbrnts-lnx-1 ovn-nbctl: ovs|00001|nbctl|INFO|Called as ovn-nbctl set address_set a16982411286042166782 addresses=10.32.2.3
``` 
openvswitch:
```
==> ovnkube.log <==
time="2018-03-21T04:04:45-05:00" level=info msg="Setting annotations ovn={\\\"ip_address\\\":\\\"10.32.2.3/24\\\", \\\"mac_address\\\":\\\"0a:00:00:00:00:09\\\", \\\"gateway_ip\\\": \\\"10.32.2.1\\\"} on pod busybox"

==> ovs-vswitchd.log <==
2018-03-21T09:04:55.735Z|00043|connmgr|INFO|br-int<->unix#0: 4 flow_mods 10 s ago (3 adds, 1 deletes)
```

On the worker:
openvswitch:
```
2018-03-21T09:04:55.736Z|00045|connmgr|INFO|br-int<->unix#4: 4 flow_mods 10 s ago (3 adds, 1 deletes)
```

Syslog:
```
Mar 21 04:04:44 esd-kbrnts-lnx-3 kubelet[111534]: I0321 04:04:44.861948  111534 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-d4s42" (UniqueName: "kubernetes.io/secret/e5f6a073-2ce6-11e8-bb77-00155d00680b-default-token-d4s42") pod "busybox" (UID: "e5f6a073-2ce6-11e8-bb77-00155d00680b")
Mar 21 04:04:44 esd-kbrnts-lnx-3 systemd[1]: Started Kubernetes transient mount for /var/lib/kubelet/pods/e5f6a073-2ce6-11e8-bb77-00155d00680b/volumes/kubernetes.io~secret/default-token-d4s42.
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:45.420913  111534 cni.go:259] Error adding network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:45.420954  111534 cni.go:220] Error while adding to cni lo network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: W0321 04:04:45.421859  111534 pod_container_deletor.go:77] Container "277f90fbcb4f7e14c445e2be43e8f23206f09c7cc3c1f54a229b22f0fcb62919" not found in pod's containers
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:45.565058  111534 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox_default" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:45.565194  111534 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox_default" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:45.565260  111534 kuberuntime_manager.go:647] createPodSandbox for pod "busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox_default" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:45 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:45.565374  111534 pod_workers.go:186] Error syncing pod e5f6a073-2ce6-11e8-bb77-00155d00680b ("busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)"), skipping: failed to "CreatePodSandbox" for "busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"busybox_default\" network: failed to find plugin \"loopback\" in path [/opt/loopback/bin /opt/cni/bin]"
Mar 21 04:04:46 esd-kbrnts-lnx-3 dockerd[111418]: time="2018-03-21T04:04:46.728046540-05:00" level=error msg="Handler for POST /v1.26/containers/277f90fbcb4f7e14c445e2be43e8f23206f09c7cc3c1f54a229b22f0fcb62919/stop returned error: Container 277f90fbcb4f7e14c445e2be43e8f23206f09c7cc3c1f54a229b22f0fcb62919 is already stopped"
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:47.105469  111534 cni.go:259] Error adding network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:47.106301  111534 cni.go:220] Error while adding to cni lo network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:47.251989  111534 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox_default" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:47.252057  111534 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox_default" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:47.252084  111534 kuberuntime_manager.go:647] createPodSandbox for pod "busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox_default" network: failed to find plugin "loopback" in path [/opt/loopback/bin /opt/cni/bin]
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: E0321 04:04:47.252235  111534 pod_workers.go:186] Error syncing pod e5f6a073-2ce6-11e8-bb77-00155d00680b ("busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)"), skipping: failed to "CreatePodSandbox" for "busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"busybox_default(e5f6a073-2ce6-11e8-bb77-00155d00680b)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"busybox_default\" network: failed to find plugin \"loopback\" in path [/opt/loopback/bin /opt/cni/bin]"
Mar 21 04:04:47 esd-kbrnts-lnx-3 kubelet[111534]: W0321 04:04:47.432467  111534 pod_container_deletor.go:77] Container "9e4cae19d3880648fafd182337b90d579d6abab37793aa1387e08dc8d4285e74" not found in pod's containers
Mar 21 04:04:47 esd-kbrnts-lnx-3 dockerd[111418]: time="2018-03-21T04:04:47.736421016-05:00" level=error msg="Handler for POST /v1.26/containers/9e4cae19d3880648fafd182337b90d579d6abab37793aa1387e08dc8d4285e74/stop returned error: Container 9e4cae19d3880648fafd182337b90d579d6abab37793aa1387e08dc8d4285e74 is already stopped"
Mar 21 04:04:47 esd-kbrnts-lnx-3 dockerd[111418]: time="2018-03-21T04:04:47.739700858-05:00" level=error msg="Handler for POST /v1.26/containers/277f90fbcb4f7e14c445e2be43e8f23206f09c7cc3c1f54a229b22f0fcb62919/stop returned error: Container 277f90fbcb4f7e14c445e2be43e8f23206f09c7cc3c1f54a229b22f0fcb62919 is already stopped"
```

It seems that it is looking for a loopback CNI but I don't have one in /opt/cni/bin
```
[04:13:49] root@esd-kbrnts-lnx-3:[~]: ls /opt/cni/bin/
ovn-k8s-cni-overlay
[04:13:57] root@esd-kbrnts-lnx-3:[~]: ls /etc/cni/net.d/
10-ovn-kubernetes.conf
[04:14:16] root@esd-kbrnts-lnx-3:[~]: cat /etc/cni/net.d/10-ovn-kubernetes.conf
{"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}
```

This is my kubelet config on the worker:
```
ExecStart=/usr/local/bin/kubelet \
        --address=10.31.0.32 \
        --network-plugin=cni \
        --allow-privileged=true \
        --pod-manifest-path=/etc/kubernetes/manifests \
        --hostname-override=esd-kbrnts-lnx-3 \
        --cluster-dns=10.32.200.10  \
        --cluster-domain=cluster.local \
        --cni-bin-dir=/opt/cni/bin \
        --cni-conf-dir=/etc/cni/net.d \
        --kubeconfig=/etc/kubernetes/kubeconfig.yaml \
        --tls-cert-file=/etc/kubernetes/tls/node.pem \
        --tls-private-key-file=/etc/kubernetes/tls/node-key.pem \
        --fail-swap-on=false
```

ovs-vsctl on both nodes:
master:
```
[04:15:39] root@esd-kbrnts-lnx-1:[/var/log]: ovs-vsctl show
18872e64-ab97-467e-b9f0-0818b2c1dfe9
    Bridge br-int
        fail_mode: secure
        Port br-int
            Interface br-int
                type: internal
        Port "ovn-c053ff-0"
            Interface "ovn-c053ff-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="10.31.0.32"}
        Port "k8s-esd-kbrnts-"
            Interface "k8s-esd-kbrnts-"
                type: internal
    ovs_version: "2.9.0"
```
worker:
```
[04:05:07] root@esd-kbrnts-lnx-3:[/var/log]: ovs-vsctl show
3d24dd54-32f5-42eb-a227-522f08652639
    Bridge br-int
        fail_mode: secure
        Port "k8s-esd-kbrnts-"
            Interface "k8s-esd-kbrnts-"
                type: internal
        Port "ovn-c1668d-0"
            Interface "ovn-c1668d-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="10.31.0.30"}
        Port br-int
            Interface br-int
                type: internal
    ovs_version: "2.9.0"
```

Any ideas would be greatly appreciated :)

**Comment by mihail-velikov** [comment]
Ok, I found the problem. It seems that I need to manually install the loopback CNI plugin and then the containers start as expected.

**Comment by rajatchopra** [comment]
Closing this issue. Re-open if needed.
