### ISSUE TITLE
OVN on Raspberry

### ISSUE THREAD

**Issue by mkomu** [openvswitch/ovn-kubernetes#452]
Hi,

I am trying out an identical OVN set up of my Intel-based set up on a Raspberry Pi (ARM). In the "nohup.log", I am getting:

panic: error setting ovn-nbctl API connection: exit status 1
  ""

goroutine 1 [running]:
main.runOvnKube(0x1348b810, 0x0, 0x0)
        /home/pirate/ovn/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:247 +0x1698
main.main.func1(0x1348b810, 0x1348b810, 0x13877c00)
        /home/pirate/ovn/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x1c
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0xab8200, 0xc7b5a4, 0x1348b810, 0x134a1e30, 0x0)
        /home/pirate/ovn/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xa8
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0x136be8c0, 0x13410090, 0x11, 0x12, 0x0, 0x0)
        /home/pirate/ovn/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x448
main.main()
        /home/pirate/ovn/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0x728

Any ideas what to check and where to continue digging?

My old set up is described here: https://github.com/openvswitch/ovn-kubernetes/issues/420

**Comment by mkomu** [comment]
The error seems to originate from this place in the source code (?):

https://github.com/openvswitch/ovn-kubernetes/blob/master/go-controller/pkg/config/config.go#L807

Which would mean that executing the command "ovn-nbctl set-connection 
<URL> -- set connection . inactivity_probe=0" (or something like that) 
fails.

**Comment by mkomu** [comment]
Sorry, ovn-central ovn-common ovn-host tools were too old. Trying with newer tools.

**Comment by mkomu** [comment]
Please close this bug, thanks and sorry!
