### ISSUE TITLE
Playbook hangs on OVS Docker network setup | Run setup_ovs_docker script

### ISSUE THREAD

**Issue by lanoxx** [openvswitch/ovn-kubernetes#488]
The playbook currently hangs in the step **OVS Docker network setup | Run setup_ovs_docker script**. This step should have a timeout of 120 seconds but it has been running for about half an hour now and has not completed yet.

On my Windows node I see that the script is still running, though it does not seem to do anything. The log file at `C:\Program Files\Cloudbase Solutions\Open vSwitch\logs\ovs-vswitchd.log` just keeps repeating the following logout put several times per second:

> 2018-11-13T10:50:09.792Z|00001|vlog|INFO|opened log file C:\Program Files\Cloudbase Solutions\Open vSwitch\logs\ovs-vswitchd.log  
> 2018-11-13T10:50:09.794Z|00002|ovs_numa|INFO|Discovered 0 NUMA nodes and 0 CPU cores  
> 2018-11-13T10:50:09.794Z|00003|reconnect|INFO|unix:C:\ProgramData\openvswitch\db.sock: connecting...  
> 2018-11-13T10:50:09.795Z|00004|reconnect|INFO|unix:C:\ProgramData\openvswitch\db.sock: connected  

I am using a Windows Server 1803 instance on AWS for the setup.

**Comment by aserdean** [comment]
The `ovs-vswitchd` restart means the extension has not been enabled.

What OVS installer are you using?

Can you please post the output of:
`ovs-vsctl show`
?

**Comment by lanoxx** [comment]
I am using the `ansible-playbook` provided in the `contrib` folder which automatically downloads the installer. According to the (openvswitch/vars/windows.yml](https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/windows/openvswitch/vars/windows.yml#L3) file it should be version: 2.7.0

The output of `ovs-vsctl show` is:

    40596ff2-9ab7-4340-a45e-56e55cb9376a
        Bridge br-ex
            Port br-ex
                Interface br-ex
                    type: internal
            Port nat
                Interface nat
            Port "vEthernet (nat)"
                Interface "vEthernet (nat)"
                type: internal

**Comment by aserdean** [comment]
It should default to 2.9 installer. https://github.com/openvswitch/ovn-kubernetes/commit/c66de8f13299184c0ffae50fab0a4dace7129e5d

Can you also include:
`ovs-vsctl --version`
`Get-NetAdapter`
`ovs-dpctl show`

**Comment by lanoxx** [comment]
You are right, it is using 2.9.x, not sure why that 
**ovs-vsctl --version:**

    ovs-vsctl (Open vSwitch) 2.9.3
    DB Schema 7.15.1

**Get-NetAdapter:**

    Name             InterfaceDescription              ifIndex Status     MacAddress         LinkSpeed
    ----             --------------------              ------- ------     ----------         ---------
    vEthernet (nat)  Hyper-V Virtual Ethernet Adapter        6 Up         00-15-5D-28-4E-C6    10 Gbps
    Ethernet 3       Amazon Elastic Network Adapter          4 Up         0A-72-37-BE-78-BE    25 Gbps

**ovs-dpctl show:**

    ovs-dpctl show
    ovs-dpctl: lost communication with the kernel device

**Comment by alinbalutoiu** [comment]
Hi @lanoxx, unless you are changing ``ovn-kubernetes-cluster.yml`` it will use by default the custom OVS. (https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/ovn-kubernetes-cluster.yml#L77-L78).

If it's possible, could you please send the output of ``ansible -m setup kube-minions-windows``?
Thanks!

**Comment by aserdean** [comment]
The chosen interface is wrong because it should be `Ethernet 3` and not `nat`. We are trying to figure out how it got into that state.
Can you also included the output of:
`Get-NetIPInterface -IncludeAllCompartments | select-Object InterfaceMetric, InterfaceAlias, AddressFamily`

**Comment by lanoxx** [comment]
Here is the output. 

**Get-NetIPInterface -IncludeAllCompartments | select-Object InterfaceMetric, InterfaceAlias, AddressFamily**

    InterfaceMetric InterfaceAlias              AddressFamily
    --------------- --------------              -------------
                 15 Ethernet 3                           IPv6
               5000 vEthernet (nat)                      IPv6
                 75 Loopback Pseudo-Interface 1          IPv6
                 15 Ethernet 3                           IPv4
               5000 vEthernet (nat)                      IPv4
                 75 Loopback Pseudo-Interface 1          IPv4

In the meantime I have setup a new Windows instance and run the playbook on it. The result is the same as the first time. The playbook currently hangs on the **Run setup_ovs_docker script** step.

**Comment by lanoxx** [comment]
Also, here is the output of `ansible -m setup kube-minions-windows`, I placed it into the following gist to keep this issue short: https://gist.github.com/lanoxx/c59112201d776bf4aab88bb755def1b2

**Comment by lanoxx** [comment]
One more thing, the `setup_ovs_docker.ps1` script executes the following command which, when I run it again in the shell outputs nothing, meaning the transparent network is not there:

    # # There should be only one transparent network
    $HNS_NW = Get-HNSNetwork | where {$_.type -eq "transparent"}

**Comment by lanoxx** [comment]
Also that network must have previously existed since the step **check if sdn is already set up** and **set hns_exists** passed.

**Comment by aserdean** [comment]
> One more thing, the `setup_ovs_docker.ps1` script executes the following command which, when I run it again in the shell outputs nothing, meaning the transparent network is not there:
> 
> ```
> # # There should be only one transparent network
> $HNS_NW = Get-HNSNetwork | where {$_.type -eq "transparent"}
> ```

That's the issue. The rest of the steps should create a transparent HNS network on top of `Ethernet 3`.
For some reason it is using the `vEthernet (nat)` interface.

One idea would be to delete the HNS network and remove it's creation before running the playbook.
A sample can be found here:
https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/windows/docker/tasks/main.yml#L17-L27

@alinbalutoiu would it make sense to also add a field for the used interface name?

**Comment by lanoxx** [comment]
I guess at the time when the script is running the net interface is the only Hns interface that exists it defaults to that one. I think the more important question is why the invokation of `New-HnsNetwork -Name {{ sdn_info.sdn_network_name }} -AddressPrefix {{OVN_SUBNET}} -Gateway {{OVN_GATEWAY_IP}} -Type Transparent -AdapterName "{{ interface_name }}"` in the step **Create HNS network** did not succeed. 

On a side note, the playbook should probably repeat the checks to see if the the network was successfully created. It currently only performs [Wait for system to become reachable over WinRM](https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/windows/kubernetes/tasks/setup_sdn.yml#L11) which does not ensure that the network was really created.

**Comment by lanoxx** [comment]
I have now manually created the HNS network using the following command:

    New-HnsNetwork -Name external -AddressPrefix 10.245.0.0/24 -Gateway 10.245.0.1 -Type Transparent -AdapterName "Ethernet 3"

I then restarted the `setup_ovs_docker.ps1`, I then lost connectivity to the VM and have not been able to connect again since then. After forcing a reboot the VM remains dead. I guess I will have to setup another instance tomorrow and try again.

**Comment by alinbalutoiu** [comment]
Hi @lanoxx , the order of your interfaces is weird. Could you please try switching the index from 0 to 1 here and try running again?
https://github.com/openvswitch/ovn-kubernetes/blob/f38e154d8a8735f5dc2054f09c69eb29cad8f5b4/contrib/roles/windows/kubernetes/tasks/set_ip_facts.yml#L24-L27

**Comment by lanoxx** [comment]
I tried with a new Windows instance today and switched the interface index to 1 in the `set_ip_facts`. With that change the `Run setup_ovs_docker script`  step is now completing successfully. However, the playbook now fails a little further down the line when it tries to ping the Gateway IP, see [attached gist](https://gist.github.com/lanoxx/60f528b6e23907b19eb388c692269870).

**Comment by lanoxx** [comment]
Yes, I have a RDP shell open and WinRM works at the moment.

**ovn-kubernetes-node.log:**

>time="2018-11-14T09:56:06Z" level=info msg="Node ec2amaz-c1dpk9d ready for ovn initialization with subnet 10.245.0.0/24"
time="2018-11-14T09:56:08Z" level=error msg="Failed to get logical router port,stderr: \"ovn-nbctl: tcp:172.33.1.108:6641: database connection failed ()\\r\\n\", error: exit status 1"
time="2018-11-14T09:56:08Z" level=error msg="exit status 1"
panic: exit status 1
>
>goroutine 1 [running]:
main.runOvnKube(0xc042180dc0, 0x0, 0x0)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:259 +0x1a51
main.main.func1(0xc042180dc0, 0xc042180dc0, 0xc0420617ff)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x32
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x1128600, 0x134a650, 0xc042180dc0, 0xc042097e00, 0x0)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xd9
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc042164e00, 0xc042080000, 0x14, 0x20, 0x0, 0x0)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x65a
main.main()
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xac5

**Comment by alinbalutoiu** [comment]
Do you have firewall enabled in AWS between the VMs? Looks like it can't reach the master node via IP and port 6641.

**Comment by lanoxx** [comment]
That was it. The script is now able to complete. Thanks a lot for the help. I will deploy a sample container now and then report back if that works.

**Comment by lanoxx** [comment]
It seems there is still another issue. I have used [a simple web service exampe](https://raw.githubusercontent.com/Microsoft/SDN/master/Kubernetes/flannel/l2bridge/manifests/simpleweb.yml) to deploy two pods on my windows node. I see that the pods are being created but then fail with `ErrPullImage`. 

Investigating this I first found that I am unable to get the logs with `./kubectl.exe logs {POD}` which gives the following error:

>Error from server: Get https://ec2amaz-c1dpk9d:10250/containerLogs/default/win-webserver-7dc569cf48-p47ff/windowswebserver: dial tcp 172.29.160.1:10250: i/o timeout

I then noticed that the IP seems strange. My IPs are in the 172.33.1.0/24 subnet, and 172.29.160.1 belongs to the `vEthernet (nat)` interface rather then to "Ethernet 3".

Running `./kubectl.exe get nodes -o wide` also shows that Kubernetes uses this IP for the Internal-IP of the node:

    NAME              STATUS   ROLES    AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION   CONTAINER-RUNTIME
    ec2amaz-c1dpk9d   Ready    <none>   113m   v1.12.0   172.29.160.1   <none>        Windows Server Datacenter   10.0.17134.345

**Comment by lanoxx** [comment]
Here is the output of those two commands:

    ubuntu@ip-172-33-1-108:~/Apps$ sudo ovn-nbctl show
    switch d6a18717-f8f9-4b65-b2b0-4fc1a97a10e0 (ec2amaz-c1dpk9d)
        port default_win-webserver-7dc569cf48-p47ff
            addresses: ["dynamic"]
        port default_win-webserver-7dc569cf48-9fpjb
            addresses: ["dynamic"]
        port k8s-ec2amaz-c1dpk9d
            addresses: ["00:15:5D:D9:7A:1A 10.245.0.2"]
        port stor-ec2amaz-c1dpk9d
            type: router
            addresses: ["00:00:00:7F:E7:79"]
            router-port: rtos-ec2amaz-c1dpk9d
    switch 9651888f-b892-4032-8905-06b68e0ed4bb (join)
        port jtor-ip-172-33-1-108
            type: router
            addresses: ["00:00:00:8C:AF:A8"]
            router-port: rtoj-ip-172-33-1-108
    router b29d080f-8d52-4f98-8d1f-7e3f4ac6bee9 (ip-172-33-1-108)
        port rtoj-ip-172-33-1-108
            mac: "00:00:00:8C:AF:A8"
            networks: ["100.64.1.1/24"]
        port rtos-ec2amaz-c1dpk9d
            mac: "00:00:00:7F:E7:79"
            networks: ["10.245.0.1/24"]
    ubuntu@ip-172-33-1-108:~/Apps$ sudo ovn-sbctl show
    Chassis "0544b98c-94fd-43dd-ae61-8a10fb63f6ae"
        hostname: "ip-172-33-1-108.eu-central-1.compute.internal"
        Encap geneve
            ip: "172.33.1.108"
            options: {csum="true"}
    Chassis "16b036e0-86ab-4f85-8d09-582aa096e6c0"
        hostname: "EC2AMAZ-C1DPK9D"
        Encap geneve
            ip: "172.29.160.1"
            options: {csum="true"}
        Port_Binding "default_win-webserver-7dc569cf48-p47ff"
        Port_Binding "default_win-webserver-7dc569cf48-9fpjb"
        Port_Binding "k8s-ec2amaz-c1dpk9d"
    Chassis "379c9783-e3e1-44e9-bd8d-effcf503b9d5"
        hostname: "ip-172-33-1-252.eu-central-1.compute.internal"
        Encap geneve
            ip: "172.33.1.252"
            options: {csum="true"}

**Comment by aserdean** [comment]
Can you also post the output of (on the windows host):
`Get-NetAdapter`
`ovs-vsctl show`
`ovs-dpctl show`
`sc.ex qc ovn-kubernetes-node`
`ipconfig`
`route print -4`

If possible?

**Comment by lanoxx** [comment]
Sorry, I missed that. In the meantime I have setup another windows instance and tried again there, but this time I also modified the index of the [ansible_ip_addresses](https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/windows/kubernetes/tasks/set_ip_facts.yml#L9-L19) and changed the index to two (found by trial and error), index 1 was the ipv6 address of the same nat interface. With that change I am now able to access the logs and the kubelet is using the correct IP address.

Currently pod deployment is still failing with an error that it cannot pull the image:

> Error from server (BadRequest): container "windowswebserver" in pod "win-webserver-7dc569cf48-6lgpc" is waiting to start: trying and failing to pull image

I am now pulling the image manually now to see if I am able to start the pod then. I will post the output of those commands in a moment.

**Comment by lanoxx** [comment]
Here is the requested output from those commands:

1. Output from the new windows node which uses the [correct internal IP](https://gist.github.com/lanoxx/d8d7fcc46397519849d6162d8e7b4d32)
2. Output from the previous windows node which uses the [wrong internal IP](https://gist.github.com/lanoxx/7d3ce507605ee8da89edd5fb074bf254)

On the new windows node I have now deployed the [simple webserver pod](https://github.com/Microsoft/SDN/blob/master/Kubernetes/flannel/l2bridge/manifests/simpleweb.yml). After manually pulling the image the pod started automatically without further intervention from my side. I can access the pod using the pod's cluster IP (e.g. 10.245.1.3) from the windows host using:

    PS C:\ Invoke-WebRequest http://10.245.1.3 -UseBasicParsing
    StatusCode        : 200
    StatusDescription : OK
    Content           : {60, 104, 116, 109...}
    RawContent        : HTTP/1.1 200 OK
                        Content-Length: 94
                        Date: Wed, 14 Nov 2018 14:03:01 GMT
                        Server: Microsoft-HTTPAPI/2.0

                        <html><body><H1>Windows Container Web Server</H1><p>IP 10.245.1.3 callerCount 4 </body></html...
    Headers           : {[Content-Length, 94], [Date, Wed, 14 Nov 2018 14:03:01 GMT], [Server, Microsoft-HTTPAPI/2.0]}
    RawContentLength  : 9

But I still cannot access the pod from the master node using either the same IP or the service IP and service port:

    ubuntu@ip-172-33-1-108 $ curl 10.245.1.3
    curl: (7) Failed to connect to 10.245.1.3 port 80: Connection timed out
    ubuntu@ip-172-33-1-108 $ curl http://10.100.224.100:30692
    curl: (7) Failed to connect to 10.100.224.100 port 30692: Connection timed out

**Comment by aserdean** [comment]
Thanks a lot for trying this out. I opened the following issues:
https://github.com/openvswitch/ovn-kubernetes/issues/492
https://github.com/openvswitch/ovn-kubernetes/issues/491

From master you can't use the same IP (`10.245.1.3`) unless you have a master/minion setup, because you don't have a route and interface to communicate with them. The `10.245.1.3` should be visible for all minions.

For the service IP, can you show the output of:
`ovn-nbctl list load_balancer`

The encap ip is wrong from ovn-kubernetes-node is wrong:  `--encap-ip="fe80::3ce1:6578:51d9:8f9e"` it should be `--encap-ip="172.33.1.39"` (let me know if I should send instructions how to set that up).

Also please include again the output of:
`ovn-nbctl show`
`ovn-sbctl show`

I want to check for duplicates in the SB db.

**Comment by lanoxx** [comment]
For some reason the second Linux node has not been joined to the cluster yet, so I can't test connectivity from the Linux node. I was am assuming that the playbook would join the second Linux node to the cluster but for some reason it has not done that. Maybe its because the playbook failed several times and I have been re-running it again with the `--limits` option set on the windows node. However, re-running it again with a limit on the second Linux node also did not help. So that's something I still have to investigate.

Anyway, here is the output:

**ovn-nbctl list load_balancer (from master node):**

    _uuid               : de7c3f6a-8878-428f-aed7-016412cdc9fd
    external_ids        : {"k8s-cluster-lb-udp"=yes}
    name                : ""
    protocol            : udp
    vips                : {}

    _uuid               : e702fad3-c930-42f4-9488-4d288af3243f
    external_ids        : {"k8s-cluster-lb-tcp"=yes}
    name                : ""
    protocol            : tcp
    vips                : {"10.100.224.100:80"="10.245.1.3:80", "10.96.0.1:443"="172.33.1.108:443"}

If you could send instructions for updating the encapsulation id that would be nice.

And here is the output of the other two commands, captured from the [master](https://gist.github.com/lanoxx/0e41f846b4417f3d9321fd848c7c3246)

**Comment by lanoxx** [comment]
> If you could send instructions for updating the encapsulation id that would be nice.

@aserdean in case you missed the sentence from my last comment, could you send me some notes on how to fix the encapsulation id?

**Comment by aserdean** [comment]
Sorry I got sidetracked with other things.

Let's take it step by step:
```
Chassis "f376e472-cb6e-4ea9-a45c-072bca59c05d"
    hostname: "EC2AMAZ-MN9BV40"
    Encap geneve
        ip: "fe80::3ce1:6578:51d9:8f9e"
        options: {csum="true"}
Chassis "0544b98c-94fd-43dd-ae61-8a10fb63f6ae"
    hostname: "ip-172-33-1-108.eu-central-1.compute.internal"
    Encap geneve
        ip: "172.33.1.108"
        options: {csum="true"}
Chassis "048cb9e3-89b8-42a1-93c6-d352043f7db2"
    hostname: "EC2AMAZ-MN9BV40"
    Encap geneve
        ip: "172.33.1.39"
        options: {csum="true"}
Chassis "16b036e0-86ab-4f85-8d09-582aa096e6c0"
    hostname: "EC2AMAZ-C1DPK9D"
    Encap geneve
        ip: "172.29.160.1"
        options: {csum="true"}
    Port_Binding "default_win-webserver-7dc569cf48-bj24c"
    Port_Binding "k8s-ec2amaz-c1dpk9d"
Chassis "72918690-1bc6-4be9-99ff-2aee7875f44e"
    hostname: "EC2AMAZ-MN9BV40"
    Encap geneve
        ip: "172.33.1.39"
        options: {csum="true"}
    Port_Binding "default_powershell-85ccc84f9c-5kfrm"
    Port_Binding "default_win-webserver-7dc569cf48-6lgpc"
    Port_Binding "k8s-ec2amaz-mn9bv40"
Chassis "379c9783-e3e1-44e9-bd8d-effcf503b9d5"
    hostname: "ip-172-33-1-252.eu-central-1.compute.internal"
    Encap geneve
        ip: "172.33.1.252"
        options: {csum="true"}
```
There are duplicate entries for `"EC2AMAZ-MN9BV40"` and we need to remove them by issuing:
ovn-sbctl chassis-del "f376e472-cb6e-4ea9-a45c-072bca59c05d" -- chassis-del "048cb9e3-89b8-42a1-93c6-d352043f7db2" -- chassis-del "72918690-1bc6-4be9-99ff-2aee7875f44e"

I sent out a PR: https://github.com/openvswitch/ovn-kubernetes/pull/499 to reduce the number of dups. 
We still need to check via the playbook if the chassis exists for a hostname clear it and let `ovn-controller` add it again.
You can delete all the chassis and they will be readded by ovn-controller again(FYI).

For the encap ip you need to delete the service and recreate it (it can by done via registry as well). I prefer to do the following:
```
sc.exe stop ovn-kubernetes-node
sc.exe delete ovn-kubernetes-node
New-Service -Name ovn-kubernetes-node "`"C:\kubernetes\servicewrapper.exe`" --log-file `"C:/kubernetes/ovn-kubernetes-node.log`" ovn-kubernetes-node `"C:\kubernetes\ovnkube.exe`" --k8s-kubeconfig=C:\kubernetes\kubeconfig.yaml --k8s-apiserver http://172.33.1.108:8080 --init-node ec2amaz-mn9bv40 --k8s-token eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tcGN2bDUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJhNzNhOWEzLWU3MmEtMTFlOC1iYzhlLTBhZjNhNzU4Njg5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.Mx7upAe03OJhgPZmdlqaKIByXgYYH-X03HY5CjB7Tr4DfN0i2k0_xpXmXDiHek7tuUZ6M49ZIMdrmNsryT0uYXx5QGWu6vkopZUgqxvVb9lg_XD-RQ2Z01RPJbTgkE56Qxfx7DFJtLA36tZuDAt7APCiMH265jvN5VjM9_opWRu5w1xsCa7QGPG0mZHaVOWpvv9-fgw-MHOByqMcXfg4z7kdhaAp2Uhepz-UTh4umoEis4dYO6Aex31x4VRxGVplm6NYeoOauEI1p7Y59GRs0Su652pjxiDR12lsRfgVJezd6CcJXIx62tuNVMjMj4F_KY01HMTI-b6qKxpkPYDwWw --nb-address `"tcp://172.33.1.108:6641`" --sb-address `"tcp://172.33.1.108:6642`" --cluster-subnet 10.245.0.0/16 --service-cluster-ip-range 10.96.0.0/12 --cni-conf-dir=`"C:/kubernetes/cni`" --cni-plugin `"ovn-k8s-cni-overlay.exe`" --encap-ip=`"172.33.1.39`"" -StartupType Automatic
sc.exe start ovn-kubernetes-node
```
I hope the escape characters preserve

**Comment by lanoxx** [comment]
@aserdean Thanks for these detailed instructions. Using that I was able to update the encapsulation id.

**Comment by lanoxx** [comment]
I spent some time today to run the Ansible playbook on a completely new set of nodes. I have deployed an nginx pod to the Linux minion and a simpleweb pod to the Windows minion. I can reach each host from its respective node, but I cannot communicate with the Windows pod from the Linux node or with the Linux pod from the Windows node. I tried both the Pod IP and the Service IP to no success.
