### ISSUE TITLE
init-gateway issue on Windows nodes after reboot

### ISSUE THREAD

**Issue by adelina-t** [openvswitch/ovn-kubernetes#516]
After Windows node reboot the ovn-kubernetes-node service is Stopped. Error:

```
time="2018-11-29T17:01:10Z" level=info msg="Node atv-win3 ready for ovn initialization with subnet 10.0.1.0/24"
time="2018-11-29T17:01:25Z" level=error msg="failed to init shared interface gateway: Failed to add logical port to router, stdout: \"\", stderr: \"ovn-nbctl: rtoe-GR_atv-win3: port already exists with mac fa:16:3e:7d:1e:e6\\r\\n\", error: exit status 1"
panic: failed to init shared interface gateway: Failed to add logical port to router, stdout: "", stderr: "ovn-nbctl: rtoe-GR_atv-win3: port already exists with mac fa:16:3e:7d:1e:e6\r\n", error: exit status 1

goroutine 1 [running]:
main.runOvnKube(0xc04222f760, 0x0, 0x0)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:259 +0x1a51
main.main.func1(0xc04222f760, 0xc04222f760, 0xc0424ff7ff)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x32
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x1135880, 0x13589b8, 0xc04222f760, 0xc0420c5380, 0x0)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xd9
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc04236a700, 0xc042084000, 0x18, 0x20, 0x0, 0x0)
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x65a
main.main()
	/tmp/ovn-kubernetes-checkout/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xac5

```

The deployed cluster worked just fine until the reboot.

**Comment by ionutbalutoiu** [comment]
I can confirm this issue as well.

**Comment by aserdean** [comment]
I think you hitting the same issue described in the comment here:
https://github.com/openvswitch/ovn-kubernetes/blob/master/contrib/roles/windows/kubernetes/tasks/setup_ovs_hns.yml#L55-L57

The main issue issue is that we read the MAC address only once the process is started and read from what was in the kernel at that time.

I'll try to see if I can add support for port changes for `vswitch`.

As a temporary workaround, you can restart `ovs-vswitchd` service if this happens.
