### ISSUE TITLE
[Ansible] Error to fetch Linux binaries to the ansible host

### ISSUE THREAD

**Issue by jesielconceicaostd** [openvswitch/ovn-kubernetes#539]
Could you help me, please?
I am trying to execute the playbook and I am receiving an error message.
I tried to increase the memory in the hosts, I tried to execute the playbook using --become and --become-user=root, but the problem continues. 

**This is the message:**
TASK [linux/kubernetes : Kubernetes bins | fetch Linux binaries to the ansible host] ***********************************************************************************************************
ok: [node1] => (item=kubectl)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [node1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

**The full traceback:**
<172.21.5.7> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<172.21.5.7> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/ubuntu/.ansible/cp/ae5b4174cc 172.21.5.7 '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1544312243.77-250979832628827/ > /dev/null 2>&1 && sleep 0'"'"''
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 104, in run
    item_results = self._run_loop(items)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 326, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 558, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/fetch.py", line 216, in run
    self._remove_tmp_path(self._connection._shell.tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 312, in _remove_tmp_path
    tmp_rm_res = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 902, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 984, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 258, in wrapped
    return_tuple = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 878, in _run
    return self._bare_run(cmd, in_data, sudoable=sudoable, checkrc=checkrc)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py", line 633, in _bare_run
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

fatal: [node1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

**Comment by lanoxx** [comment]
I think this is due to an out-of-memory error. Possible duplicate #494 which is being addressed by pull request #506

**Comment by lanoxx** [comment]
I think this can be closed.
