### ISSUE TITLE
Failed to localnet gateway: Failed to add logical port to router; "port already exists"

### ISSUE THREAD

**Issue by CM2Walki** [openvswitch/ovn-kubernetes#556]
I've been running into this issue on reboots of my master:

```Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovn-nbctl[4017]: ovs|00002|db_ctl_base|ERR|rtoe-GR_mstr-0.XXXXXXXXXXXXXXX.de: port already exists with mac 02:00:00:6e:00:21
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: time="2018-12-18T16:12:15Z" level=error msg="failed to localnet gateway: Failed to add logical port to router, stdout: \"\", stderr: \"ovn-nbct
l: rtoe-GR_mstr-0.XXXXXXXXXXXXXXX.de: port already exists with mac 02:00:00:6e:00:21\\n\", error: exit status 1"
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: panic: failed to localnet gateway: Failed to add logical port to router, stdout: "", stderr: "ovn-nbctl: rtoe-GR_mstr-0.XXXXXXXXXXXXXXX.de: port already exists with mac 02:00:00:6e:00:21\n", error: exit status 1
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: goroutine 1 [running]:
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: main.runOvnKube(0xc0003a6f20, 0x0, 0x0)
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]:         /opt/k8s/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:259 +0x
164d
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: main.main.func1(0xc0003a6f20, 0xc0003a6f20, 0xc00014d81f)
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]:         /opt/k8s/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x
2b
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x10b70c0, 0x12e23e8, 0xc0003a6f20, 0xc0001bd980,
 0x0)
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]:         /opt/k8s/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/a
pp.go:501 +0xc8
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc00042ce00, 0xc000001b00, 0x17, 0x18, 0x0, 0x0)
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]:         /opt/k8s/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/a
pp.go:268 +0x5b7
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]: main.main()
Dec 18 16:12:15 mstr-0.XXXXXXXXXXXXXXX.de ovnkube[3933]:         /opt/k8s/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0x
a4b
```
I managed to track it down to this:
https://github.com/openvswitch/ovn-kubernetes/blob/f05757a5f6593b157d666c93e763dcd0436fae6e/go-controller/pkg/cni/helper_linux.go#L154-L156
Could it be that this command is missing the "--if-exists"?

**Comment by girishmg** [comment]
@CM2Walki It could not be because of the code you mentioned above. It is something else, and it is with regard to how we create logical router port for the gateway router.

Are you using daemonset or the ovnkube binary? Can you share the output of the following when you see the above error?

```
$ ovn-nbctl find logical_router_port mac="02\:00\:00\:6e\:00\:21"
(or whatever is the MAC address that we are duplicating)
```

**Comment by CM2Walki** [comment]
I'm using the ovnkube binary.

```
ovn-nbctl find logical_router_port mac="02\:00\:00\:6e\:00\:21"
_uuid               : 12481c7b-9bdd-4165-b9d0-3d8083b2aa35
enabled             : []
external_ids        : {gateway-physical-ip=yes}
gateway_chassis     : []
ipv6_ra_configs     : {}
mac                 : "02:00:00:6e:00:21"
name                : "rtoe-GR_mstr-0.XXXXXXXXXXXXXXX.de"
networks            : ["10.155.208.132/21"]
options             : {}
peer                : []
```

Thanks for looking into the issue!

**Comment by CM2Walki** [comment]
#516 
Seems to be the exact same issue and was fixed for Windows. Is it possible to replicate this on for the Linux setup?

**Comment by CM2Walki** [comment]
Issue was because of misconfiguration. Basically, running ovnkube with -init-gateways once and then later again but with " -init-gateways -gateway-localnet". This should replicate the error.
Sorry for the time waste.
