### ISSUE TITLE
Failed to create a single common distributed router for the cluster | failed: signal: alarm clock

### ISSUE THREAD

**Issue by ylhyh** [openvswitch/ovn-kubernetes#625]
I have deployed HA OVN central database(172.16.126.205,172.16.126.206,172.16.126.207) by following the guid [HA.md](https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md).

When I running ovnkube on the Kubernetes master node, it occurs the following error:
```
time="2019-02-20T16:14:21+08:00" level=info msg="Setting annotations ovn_host_subnet=10.112.3.0/24 on node node001"
time="2019-02-20T16:14:21+08:00" level=info msg="Created HostSubnet 10.112.3.0/24"
time="2019-02-20T16:14:36+08:00" level=error msg="Failed to create a single common distributed router for the cluster, stdout: \"\", stderr: \"2019-02-20T08:14:36Z|00002|fatal_signal|WARN|terminating with signal 14 (Alarm clock)\\n\", error: OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.205:6643,tcp:172.16.126.206:6643,tcp:172.16.126.207:6643 --timeout=15 -- --may-exist lr-add ovn_cluster_router -- set logical_router ovn_cluster_router external_ids:k8s-cluster-router=yes' failed: signal: alarm clock"
time="2019-02-20T16:14:36+08:00" level=error msg="Failed to setup master (OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.205:6643,tcp:172.16.126.206:6643,tcp:172.16.126.207:6643 --timeout=15 -- --may-exist lr-add ovn_cluster_router -- set logical_router ovn_cluster_router external_ids:k8s-cluster-router=yes' failed: signal: alarm clock)"
time="2019-02-20T16:14:36+08:00" level=error msg="OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.205:6643,tcp:172.16.126.206:6643,tcp:172.16.126.207:6643 --timeout=15 -- --may-exist lr-add ovn_cluster_router -- set logical_router ovn_cluster_router external_ids:k8s-cluster-router=yes' failed: signal: alarm clock"

```

systemd file of ovn-kubernetes
```
[Unit]
Description=OVN Kubernetes daemon
After=ovsdb-server.service ovs-delete-transient-ports.service ovs-vswitchd.service openvswitch.service ovn-northd.service ovn-controller.service
Requires=ovsdb-server.service
Requires=ovs-delete-transient-ports.service 
Requires=ovs-vswitchd.service
Requires=openvswitch.service
Requires=ovn-northd.service
Requires=ovn-controller.service

[Service]
Type=simple
ExecStart=/usr/bin/ovnkube --init-master=master1 -init-node=master1 --net-controller -cluster-subnet=10.112.0.0/16 -service-cluster-ip-range=10.96.0.0/16 --config-file=/etc/openvswitch/ovn_k8s.conf


[Install]
WantedBy=multi-user.target
```
File content of ovn_k8s.conf
```
[default]

[logging]
loglevel=4
logfile=/var/log/openvswitch/ovn-kubernetes.log

[cni]
conf-dir=/etc/cni/net.d
plugin=ovn-k8s-cni-overlay

[kubernetes]
apiserver=https://172.16.126.202:6443
token=XXXXX
cacert=/etc/kubernetes/pki/ca.crt

[ovnnorth]
address=tcp://172.16.126.205:6643,tcp://172.16.126.206:6643,tcp://172.16.126.207:6643

[ovnsouth]
address=tcp://172.16.126.205:6644,tcp://172.16.126.206:6644,tcp://172.16.126.207:6644
```

Can anyone tell me how to diagnosis this error?

**Comment by ylhyh** [comment]
it occurs the error below if I run ovnkube in frontend:

```
# sudo /usr/bin/ovnkube --init-master=master1 --init-node=master1 --net-controller --cluster-subnet=10.112.0.0/16 --service-cluster-ip-range=10.96.0.0/16 --loglevel=4 --logfile=/var/log/openvswitch/ovn-kubernetes.log --nb-address=tcp://172.16.126.205:6643,tcp://172.16.126.206:6643,tcp://172.16.126.207:6643 --sb-address=tcp://172.16.126.205:6644,tcp://172.16.126.206:6644,tcp://172.16.126.207:6644 --k8s-apiserver=https://172.16.126.202:6443 --k8s-token=XXX --k8s-cacert=/etc/kubernetes/pki/ca.crt
panic: OVN command '/bin/ovn-nbctl --db=tcp:172.16.126.205:6643,tcp:172.16.126.206:6643,tcp:172.16.126.207:6643 --timeout=15 -- --may-exist lr-add ovn_cluster_router -- set logical_router ovn_cluster_router external_ids:k8s-cluster-router=yes' failed: signal: alarm clock

goroutine 1 [running]:
main.runOvnKube(0xc0004d9080, 0x0, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:255 +0x1072
main.main.func1(0xc0004d9080, 0xc0004d9080, 0xc0004e181f)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x2b
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x10bd600, 0x12e8c30, 0xc0004d9080, 0xc0000e3980, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc0000dce00, 0xc00003a1a0, 0xd, 0xd, 0x0, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x5b7
main.main()
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xa54
```

**Comment by shettyg** [comment]
It likely means that the cluster is not healthy.

**Comment by girishmg** [comment]
@ylhyh can you also make sure if your OVN NB and SB endpoints are correct? I see they are using 6643 and 6644? They are RAFT cluster ports. You should be using 6641 for OVN NB and 6642 for OVN SB.

**Comment by ylhyh** [comment]
@shettyg 

I have used the external central database. @girishmg tell me that external central database is not support for now. So I build another central database cluster on 3 Kubernetes Master nodes:172.16.126.202, 172.16.126.203, 172.16.126.204.

But it still throw the exceptions: 
```

# sudo /usr/bin/ovnkube --init-master=master1 --init-node=master1 --net-controller --cluster-subnet=10.112.0.0/16 --service-cluster-ip-range=10.96.0.0/16 --loglevel=4 --logfile=/var/log/openvswitch/ovn-kubernetes.log --nb-address=tcp://172.16.126.202:6643,tcp://172.16.126.203:6643,tcp://172.16.126.204:6643 --sb-address=tcp://172.16.126.202:6644,tcp://172.16.126.203:6644,tcp://172.16.126.204:6644 --k8s-apiserver=https://apiserver.q1lan.k8s:6443 --k8s-token=XXXXX --k8s-cacert=/etc/kubernetes/pki/ca.crt

panic: OVN command '/bin/ovn-nbctl --db=tcp:172.16.126.202:6643,tcp:172.16.126.203:6643,tcp:172.16.126.204:6643 --timeout=15 -- --may-exist lr-add ovn_cluster_router -- set logical_router ovn_cluster_router external_ids:k8s-cluster-router=yes' failed: signal: alarm clock

goroutine 1 [running]:
main.runOvnKube(0xc000175080, 0x0, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:255 +0x1072
main.main.func1(0xc000175080, 0xc000175080, 0xc00018581f)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x2b
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x10bd600, 0x12e8c30, 0xc000175080, 0xc0000ef980, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc000156e00, 0xc00003a1a0, 0xd, 0xd, 0x0, 0x0)
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x5b7
main.main()
	/root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xa54

```

What does the error mean?

The cluster status shows below:
```
[root@master1 ~]# ovs-appctl -t /var/run/openvswitch/ovnnb_db.ctl cluster/status OVN_Northbound
33ad
Name: OVN_Northbound
Cluster ID: 6c82 (6c825369-ad18-4793-8521-81a15a138751)
Server ID: 33ad (33ad0084-c747-45a8-9de1-86c51691cb7d)
Address: tcp:172.16.126.202:6643
Status: cluster member
Role: leader
Term: 1
Leader: self
Vote: self

Log: [2, 6]
Entries not yet committed: 0
Entries not yet applied: 0
Connections: <-6412 ->6412 <-b704 ->b704
Servers:
    33ad (33ad at tcp:172.16.126.202:6643) (self) next_index=2 match_index=5
    b704 (b704 at tcp:172.16.126.204:6643) next_index=6 match_index=5
    6412 (6412 at tcp:172.16.126.203:6643) next_index=6 match_index=5
[root@master1 ~]# ovs-appctl -t /var/run/openvswitch/ovnsb_db.ctl cluster/status OVN_Southbound
30bf
Name: OVN_Southbound
Cluster ID: a0db (a0db4d79-f6eb-48a7-bab4-716b7211c4b8)
Server ID: 30bf (30bffe92-9e78-4a70-8bc7-4e9192ab321e)
Address: tcp:172.16.126.202:6644
Status: cluster member
Role: leader
Term: 1
Leader: self
Vote: self

Log: [2, 5]
Entries not yet committed: 0
Entries not yet applied: 0
Connections: <-0000 <-157a ->157a <-650c ->650c
Servers:
    650c (650c at tcp:172.16.126.204:6644) next_index=5 match_index=4
    157a (157a at tcp:172.16.126.203:6644) next_index=5 match_index=4
    30bf (30bf at tcp:172.16.126.202:6644) (self) next_index=2 match_index=4

```

**Comment by shettyg** [comment]
As @girishmg pointed out, looks like you are using wrong port numbers.

The doc at https://github.com/openvswitch/ovn-kubernetes/blob/master/docs/ha.md does not have 6643 written anywhere

**Comment by ylhyh** [comment]
@girishmg , how to change the listening port? I have used the way that mentioned in HA.md to create the cluster, it's automatically bind to 6643 and 6644

**Comment by girishmg** [comment]
Try this out 

- on the Leader of the RAFT cluster for NB
   `ovn-nbctl set-connection ptcp:6641`
- on the leader of the RAFT cluster for SB
    `ovn-sbctl set-connection ptctp:6642`

How do you find who is the leader? For that use this..
```
ovs-appctl -t /var/run/openvswitch/ovnnb_db.ctl cluster/status OVN_Northbound
ovs-appctl -t /var/run/openvswitch/ovnsb_db.ctl cluster/status OVN_Southbound
```

**Comment by shettyg** [comment]
@ylhyh I think you are confusing port numbers. The 6643 and 6644 are used as peer ports for clustered database for RAFT protocol to work. You should still use 6641 and 6642 to access OVN databases.

**Comment by ylhyh** [comment]
@girishmg 
After execute "ovn-nbctl/ovn-sbctl set-connection ...", there are 2 ovsdb-server processes are being listen on 6641 and 6642 ports:
```
# netstat -tplun
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 172.16.126.202:6643     0.0.0.0:*               LISTEN      9508/ovsdb-server   
tcp        0      0 172.16.126.202:6644     0.0.0.0:*               LISTEN      9554/ovsdb-server   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4270/sshd           
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      3664/kubelet        
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      6473/kube-proxy     
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      6239/kube-scheduler 
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      6398/kube-controlle 
tcp        0      0 127.0.0.1:34479         0.0.0.0:*               LISTEN      3664/kubelet        
tcp        0      0 0.0.0.0:6641            0.0.0.0:*               LISTEN      9508/ovsdb-server   
tcp        0      0 0.0.0.0:6642            0.0.0.0:*               LISTEN      9554/ovsdb-server   
tcp6       0      0 :::10259                :::*                    LISTEN      6239/kube-scheduler 
tcp6       0      0 :::22                   :::*                    LISTEN      4270/sshd           
tcp6       0      0 :::10250                :::*                    LISTEN      3664/kubelet        
tcp6       0      0 :::6443                 :::*                    LISTEN      6464/kube-apiserver 
tcp6       0      0 :::10256                :::*                    LISTEN      6473/kube-proxy     
tcp6       0      0 :::10257                :::*                    LISTEN      6398/kube-controlle

```

And ovnkube can success  connect to central database, but a new error occured of "Failed to add logical port to router, ...  router UUID not found".
Am I missing steps? And why ask people to manually execute ovn-nbctl/ovn-nbstl to set port number instead of let ovnkube do that?
```
time="2019-02-21T03:10:25+08:00" level=info msg="Node master1 ready for ovn initialization with subnet 10.112.0.0/24"
time="2019-02-21T03:10:26+08:00" level=error msg="Failed to add logical switch master1's loadbalancer, stdout: \"\", stderr: \"2019-02-20T19:10:26Z|00003|ovsdb_idl|WARN|transaction error: {\\\"details\\\":\\\"Table Logical_Switch column load_balancer row cf3b0c32-be4b-48b6-abf9-e93afdc7ebee references nonexistent row b84d8743-605d-4e33-bfe2-b2f0bf190265 in table Load_Balancer.\\\",\\\"error\\\":\\\"referential integrity violation\\\"}\\novn-nbctl: transaction error: {\\\"details\\\":\\\"Table Logical_Switch column load_balancer row cf3b0c32-be4b-48b6-abf9-e93afdc7ebee references nonexistent row b84d8743-605d-4e33-bfe2-b2f0bf190265 in table Load_Balancer.\\\",\\\"error\\\":\\\"referential integrity violation\\\"}\\n\", error: OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 add logical_switch master1 load_balancer b84d8743-605d-4e33-bfe2-b2f0bf190265' failed: exit status 1"
time="2019-02-21T03:10:26+08:00" level=error msg="OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 add logical_switch master1 load_balancer b84d8743-605d-4e33-bfe2-b2f0bf190265' failed: exit status 1"
time="2019-02-21T03:11:21+08:00" level=info msg="Node master1 ready for ovn initialization with subnet 10.112.0.0/24"
time="2019-02-21T03:11:21+08:00" level=error msg="Failed to add logical port to router, stderr: \"ovn-nbctl: 59fae5af-ce89-4724-b92f-20123e2d1f61: router UUID not found\\n\", error: OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 --may-exist lrp-add 59fae5af-ce89-4724-b92f-20123e2d1f61 rtos-master1 00:00:00:2C:44:78 10.112.0.1/24' failed: exit status 1"
time="2019-02-21T03:11:21+08:00" level=error msg="OVN command '/usr/bin/ovn-nbctl --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 --may-exist lrp-add 59fae5af-ce89-4724-b92f-20123e2d1f61 rtos-master1 00:00:00:2C:44:78 10.112.0.1/24' failed: exit status 1"
```
@shettyg 
Yes, I'm confused with the port numbers. what is the  difference between "ovn-northd" SERVICE and manually to execute "/usr/share/openvswitch/scripts/ovn-ctl start_nb_ovsdb"?
After complete centrol database cluster initialization, how to make the central database auto-start on next system reboot?

Sometimes the ovnctl start_nb_ovsdb/start_sb_ovsdb shows below error, what does the error mean?
```
# /usr/share/openvswitch/scripts/ovn-ctl start_nb_ovsdb
ovsdb-tool: ovsdb error: /etc/openvswitch/ovnnb_db.db: cannot apply this operation to clustered database file
[root@master1 ~]# /usr/share/openvswitch/scripts/ovn-ctl start_sb_ovsdb
ovsdb-tool: ovsdb error: /etc/openvswitch/ovnsb_db.db: cannot apply this operation to clustered database file
```

**Comment by ylhyh** [comment]
After many times reset/reconfigure, the Linux Minion node works. But there are still two issues blocked me:
1. coredns pod in kube-system stucking CrashLoopBackUp by the error blow:
`E0221 11:21:22.384157       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host`

2. Can't run ovnkube on Windows Minion node, it's shows below error message:
```
panic: OVN command 'C:\Program Files\Cloudbase Solutions\Open vSwitch\bin\ovn-nbctl.exe --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 --if-exist get logical_router_port rtos-node009 mac' failed: exit status 1

goroutine 1 [running]:
main.runOvnKube(0xc0003cd340, 0x0, 0x0)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:267 +0xf6b
main.main.func1(0xc0003cd340, 0xc0003cd340, 0xc00016381f)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x32
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x1086760, 0x12a4750, 0xc0003cd340, 0xc0000d5980, 0x0)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xcf
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc0002b6e00, 0xc0000a4000, 0x8, 0x8, 0x0, 0x0)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x5be
main.main()
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xa5b
```

if I run "ovn-nbctl.exe --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 --if-exist get logical_router_port rtos-node009 mac" in cmd, it says bad port number "6641,tcp": 
```
2019-02-21T11:26:04Z|00001|socket_util|ERR|172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641: bad port number "6641,tcp"
2019-02-21T11:26:04Z|00002|stream_tcp|ERR|tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641: connect: Unknown error
ovn-nbctl: tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641: database connection failed (Unknown error)
```
if I remove the tcp: prefix to run "ovn-nbctl.exe --db=tcp:172.16.126.202:6641,tcp:172.16.126.203:6641,tcp:172.16.126.204:6641 --timeout=15 --if-exist get logical_router_port rtos-node009 mac", it says database connection failed with Unknown error:
```
ovn-nbctl.exe --db=172.16.126.202:6641,172.16.126.203:6641,172.16.126.204:6641 --timeout=15 --if-exist get logical_router_port rtos-node009 mac
ovn-nbctl: 172.16.126.202:6641,172.16.126.203:6641,172.16.126.204:6641: database connection failed (Unknown error)
```
I can successfully telnet to the database endpoints: 172.16.126.202:6641/172.16.126.203:6641/172.16.126.204:6641 from the Windows Minion node.

How to make it work? I'm almost crazy...

**Comment by ylhyh** [comment]
I think the database connection is due to openvswitch 2.7.0 does not support the connection mehtod of HA central database. So I created a VIP point to leader node, Finally, very regrettable, it says:
```

panic: Not implemented yet on Windows

goroutine 1 [running]:
main.runOvnKube(0xc000471080, 0x0, 0x0)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:267 +0xf6b
main.main.func1(0xc000471080, 0xc000471080, 0xc0004db81f)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:117 +0x32
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.HandleAction(0x1086760, 0x12a4750, 0xc000471080, 0xc0000d1d40, 0x0)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:501 +0xcf
github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli.(*App).Run(0xc0002fae00, 0xc0000b2000, 0x8, 0x8, 0x0, 0x0)
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/app.go:268 +0x5be
main.main()
        /root/github.com/openvswitch/ovn-kubernetes/go-controller/_output/go/src/github.com/openvswitch/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:120 +0xa5b
```

**Comment by shettyg** [comment]
If your goal is windows installation, have you considered looking at the ansible files that create Windows node and installation? That should help you follow step by step instructions.

If the goal is Linux installation, consider looking at the setup-master.sh and setup-minion.sh files in vagrant/provisioning directory.

**Comment by ylhyh** [comment]
I am new on OVN, after a few days of study, the Kubernetes cluster with OVN network work normally except the Window minion and NodePort mode. 

I have 3 master nodes services for  Kubernetes master and OVN central database. I have also created systemd service file and starter scripts to auto-start central database cluster and determine the leader node.

I will open new thread for any other questions. 

Thanks a lot , @girishmg , @shettyg
