### ISSUE TITLE
Random crashes in watcher

### ISSUE THREAD

**Issue by pires** [openvswitch/ovn-kubernetes#84]
From time to time, I see this in the `ovn-k8s-watcher` logs:
```
ovn-k8s-watcher[10746]: ovs| 2533| watcher  (GreenThread-3) | ERR | Failure in watcher EndpointWatcher
                                                        Traceback (most recent call last):
                                                          File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/watcher/watcher.py", line 59, in _process_func
                                                            watcher.process()
                                                          File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/watcher/endpoint_watcher.py", line 80, in process
                                                            self._process_endpoint_event)
                                                          File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/common/util.py", line 77, in process_stream
                                                            line = next(data_stream)
                                                        StopIteration
ovn-k8s-watcher[10746]: ovs| 2534| watcher  (GreenThread-3) | WARN | Regenerating watcher because of "" and reconnecting to stream using function _create_k8s_endpoint_watcher
gcp-next-master ovn-k8s-watcher[10746]: 2017-02-24T16:14:09Z | 2533| watcher  (GreenThread-3) | ERR | Failure in watcher EndpointWatcher
 ovn-k8s-watcher[10746]: Traceback (most recent call last):
ovn-k8s-watcher[10746]:   File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/watcher/watcher.py", line 59, in _process_func
ovn-k8s-watcher[10746]:     watcher.process()
ovn-k8s-watcher[10746]:   File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/watcher/endpoint_watcher.py", line 80, in process
ovn-k8s-watcher[10746]:     self._process_endpoint_event)
ovn-k8s-watcher[10746]:   File "/usr/local/lib/python2.7/dist-packages/ovn_k8s/common/util.py", line 77, in process_stream
ovn-k8s-watcher[10746]:     line = next(data_stream)
ovn-k8s-watcher[10746]: StopIteration
ovn-k8s-watcher[10746]: 2017-02-24T16:14:09Z | 2534| watcher  (GreenThread-3) | WARN | Regenerating watcher because of "" and reconnecting to stream using function _create_k8s_endpoint_watcher
```

Is this normal?

**Comment by shettyg** [comment]
Yes. That is normal. The stream connection to API server times out and then you reconnect. I think it needs to be improved. 

1. I have heard that the 'timeout' is configurable. So that needs to be investigated.
2. Right now, during a reconnection, you effectively, get all the events again, and we waste cycles processing them.  Something better needs to be done here.

**Comment by pires** [comment]
Thank you for clarifying. I'm OK if you want to close the issue but I'll leave it open in case someone else comes looking.

**Comment by russellb** [comment]
If this is normal / expected, it would be nice to catch the exception and just log that a reconnection is happening.  A traceback always looks like an unexpected error condition to me.

**Comment by shettyg** [comment]
I sent in a pull request that does not show backtrace for this particular type of issue.
